### ISSUE TITLE
1.19.4?

### ISSUE THREAD

**Issue by RaptaG** [PssbleTrngle/KnowMyName#3]
### Describe the feature you have in mind.

Support for the latest MC version :)

**Comment by Julienraptor01** [comment]
+ 1.19.4 pls ?

**Comment by PssbleTrngle** [comment]
I have not tried  it myself yet, but it should probably just work with 1.19.4 out of the box

**Comment by GhostIsBeHere** [comment]
Haven't tested it on 1.19.4. However, on 1.19.3, it loads/doesn't crash but doesn't actually tell players the block's name.

**Comment by PssbleTrngle** [comment]
I have uploaded a new version (1.2.0) which should work again for both 1.19.3 and 1.19.4

**Comment by RaptaG** [comment]
Thank you!!
