### ISSUE TITLE
Description Wrong in Prism launcher and Mod Menu Displays After Downloading

### ISSUE THREAD

**Issue by NicKnack819** [PssbleTrngle/KnowMyName#6]
### What happened?

Proper Description from Modirinth:
![image](https://github.com/PssbleTrngle/KnowMyName/assets/60555295/361bb265-1fef-4d14-a9d1-235408eff867)

Shown Description In launcher and In Game:
![image](https://github.com/PssbleTrngle/KnowMyName/assets/60555295/a0bf5fb7-e37a-4c5f-9792-ab803ca831ef)

![image](https://github.com/PssbleTrngle/KnowMyName/assets/60555295/712aa0c3-7e55-479a-abb0-c3b00847489d)

### Loader

fabric

### Mod Version

Fabric 1.3.0

### Minecraft Version

1.19.4

**Comment by NicKnack819** [comment]
Correction It took on the mod description of [DataTrades](https://github.com/PssbleTrngle/DataTrades) somehow?

**Comment by NicKnack819** [comment]
Came back to inform that this is still a bug...

**Comment by PssbleTrngle** [comment]
True, this is not critical at all but will fix for future releases
